### ISSUE TITLE
Compile prompt error

### ISSUE THREAD

**Issue by hunkyu** [rsasaki0109/li_slam_ros2#1]
scanmatcher prompt:
<command-line>:0:1: error: macro names must be identifiers

Found in image_projection.cpp 
`add_executable(image_projection src/image_projection.cpp)
  ament_target_dependencies(image_projection
    rclcpp
    rclcpp_components
    tf2_ros
    tf2_geometry_msgs
    tf2_sensor_msgs
    tf2_eigen
    geometry_msgs
    sensor_msgs
    nav_msgs
    #liosam_msgs
    PCL
    OpenCV
  )`
I do not compile and generate image_projection, but there is no problem

**Comment by rsasaki0109** [comment]
Hmmm, I've never faced that error before, so I don't know how to deal with it

**Comment by hunkyu** [comment]
Which version of ros2 are you currently using? ros2 dashing?

**Comment by rsasaki0109** [comment]
ros2 foxy

**Comment by hunkyu** [comment]
Finished <<< ndt_omp_ros2 [38.6s]
Starting >>> graph_based_slam
Starting >>> scanmatcher                        
[Processing: graph_based_slam, scanmatcher]                                                      
[Processing: graph_based_slam, scanmatcher]                                         
--- stderr: scanmatcher                                                             
** WARNING ** io features related to ensenso will be disabled
** WARNING ** io features related to davidSDK will be disabled
** WARNING ** io features related to dssdk will be disabled
** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
** WARNING ** io features related to libusb-1.0 will be disabled
** WARNING ** visualization features related to ensenso will be disabled
** WARNING ** visualization features related to davidSDK will be disabled
** WARNING ** visualization features related to dssdk will be disabled
** WARNING ** visualization features related to rssdk will be disabled
<command-line>:0:1: error: macro names must be identifiers
/home/gzxsmapper/ros2_lio_ws/src/li_slam_ros2-master/scanmatcher/src/image_projection.cpp:169:65: warning: ‘ConstPtr’ is deprecated [-Wdeprecated-declarations]
   void imuHandler(const sensor_msgs::msg::Imu::ConstPtr & imuMsg)
                                                                 ^
/home/gzxsmapper/ros2_lio_ws/src/li_slam_ros2-master/scanmatcher/src/image_projection.cpp:194:77: warning: ‘ConstPtr’ is deprecated [-Wdeprecated-declarations]
   void odometryHandler(const nav_msgs::msg::Odometry::ConstPtr & odometryMsg)
                                                                             ^
/home/gzxsmapper/ros2_lio_ws/src/li_slam_ros2-master/scanmatcher/src/image_projection.cpp:200:82: warning: ‘ConstPtr’ is deprecated [-Wdeprecated-declarations]
   void cloudHandler(const sensor_msgs::msg::PointCloud2::ConstPtr & laserCloudMsg)
                                                                                  ^
/home/gzxsmapper/ros2_lio_ws/src/li_slam_ros2-master/scanmatcher/src/image_projection.cpp:219:85: warning: ‘ConstPtr’ is deprecated [-Wdeprecated-declarations]
   bool cachePointCloud(const sensor_msgs::msg::PointCloud2::ConstPtr & laserCloudMsg)
                                                                                     ^
/home/gzxsmapper/ros2_lio_ws/src/li_slam_ros2-master/scanmatcher/src/image_projection.cpp: In constructor ‘ImageProjection::ImageProjection(const rclcpp::NodeOptions&)’:
/home/gzxsmapper/ros2_lio_ws/src/li_slam_ros2-master/scanmatcher/src/image_projection.cpp:109:60: warning: ‘ConstPtr’ is deprecated [-Wdeprecated-declarations]
       [this](const sensor_msgs::msg::Imu::ConstPtr msg) -> void
                                                            ^~~~
/home/gzxsmapper/ros2_lio_ws/src/li_slam_ros2-master/scanmatcher/src/image_projection.cpp:116:62: warning: ‘ConstPtr’ is deprecated [-Wdeprecated-declarations]
       [this](const nav_msgs::msg::Odometry::ConstPtr msg) -> void
                                                              ^~~~
/home/gzxsmapper/ros2_lio_ws/src/li_slam_ros2-master/scanmatcher/src/image_projection.cpp:123:68: warning: ‘ConstPtr’ is deprecated [-Wdeprecated-declarations]
       [this](const sensor_msgs::msg::PointCloud2::ConstPtr msg) -> void
                                                                    ^~~~
/home/gzxsmapper/ros2_lio_ws/src/li_slam_ros2-master/scanmatcher/src/imu_preintegration.cpp:196:73: warning: ‘ConstPtr’ is deprecated [-Wdeprecated-declarations]
   void odometryHandler(const nav_msgs::msg::Odometry::ConstPtr & odomMsg)
                                                                         ^
/home/gzxsmapper/ros2_lio_ws/src/li_slam_ros2-master/scanmatcher/src/imu_preintegration.cpp:415:66: warning: ‘ConstPtr’ is deprecated [-Wdeprecated-declarations]
   void imuHandler(const sensor_msgs::msg::Imu::ConstPtr & imu_raw)
                                                                  ^
/home/gzxsmapper/ros2_lio_ws/src/li_slam_ros2-master/scanmatcher/src/imu_preintegration.cpp: In constructor ‘IMUPreintegration::IMUPreintegration(const rclcpp::NodeOptions&)’:
/home/gzxsmapper/ros2_lio_ws/src/li_slam_ros2-master/scanmatcher/src/imu_preintegration.cpp:125:60: warning: ‘ConstPtr’ is deprecated [-Wdeprecated-declarations]
       [this](const sensor_msgs::msg::Imu::ConstPtr msg) -> void
                                                            ^~~~
/home/gzxsmapper/ros2_lio_ws/src/li_slam_ros2-master/scanmatcher/src/imu_preintegration.cpp:130:62: warning: ‘ConstPtr’ is deprecated [-Wdeprecated-declarations]
       [this](const nav_msgs::msg::Odometry::ConstPtr msg) -> void
                                                              ^~~~
In file included from /usr/include/pcl-1.8/pcl/sample_consensus/sac_model.h:52:0,
                 from /usr/include/pcl-1.8/pcl/sample_consensus/sac.h:45,
                 from /usr/include/pcl-1.8/pcl/sample_consensus/ransac.h:44,
                 from /usr/include/pcl-1.8/pcl/registration/icp.h:45,
                 from /home/gzxsmapper/ros2_lio_ws/src/li_slam_ros2-master/scanmatcher/include/scanmatcher/utility.h:55,
                 from /home/gzxsmapper/ros2_lio_ws/src/li_slam_ros2-master/scanmatcher/src/image_projection.cpp:31:
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h: In function ‘void __static_initialization_and_destruction_0(int, int)’:
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: warning: ‘pcl::SAC_SAMPLE_SIZE’ is deprecated: This map is deprecated and is kept only to prevent breaking existing user code. Starting from PCL 1.8.0 model sample size is a protected member of the SampleConsensusModel class [-Wdeprecated-declarations]
   SAC_SAMPLE_SIZE (sample_size_pairs, sample_size_pairs + sizeof (sample_size_pairs) / sizeof (SampleSizeModel));
   ^~~~~~~~~~~~~~~
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: note: declared here
make[2]: *** [CMakeFiles/image_projection.dir/src/image_projection.cpp.o] Error 1
make[1]: *** [CMakeFiles/image_projection.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
In file included from /usr/include/pcl-1.8/pcl/sample_consensus/sac_model.h:52:0,
                 from /usr/include/pcl-1.8/pcl/sample_consensus/sac.h:45,
                 from /usr/include/pcl-1.8/pcl/sample_consensus/ransac.h:44,
                 from /usr/include/pcl-1.8/pcl/registration/icp.h:45,
                 from /home/gzxsmapper/ros2_lio_ws/src/li_slam_ros2-master/scanmatcher/include/scanmatcher/utility.h:55,
                 from /home/gzxsmapper/ros2_lio_ws/src/li_slam_ros2-master/scanmatcher/include/scanmatcher/scanmatcher_component.h:61,
                 from /home/gzxsmapper/ros2_lio_ws/src/li_slam_ros2-master/scanmatcher/src/scanmatcher_component.cpp:1:
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h: In function ‘void __static_initialization_and_destruction_0(int, int)’:
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: warning: ‘pcl::SAC_SAMPLE_SIZE’ is deprecated: This map is deprecated and is kept only to prevent breaking existing user code. Starting from PCL 1.8.0 model sample size is a protected member of the SampleConsensusModel class [-Wdeprecated-declarations]
   SAC_SAMPLE_SIZE (sample_size_pairs, sample_size_pairs + sizeof (sample_size_pairs) / sizeof (SampleSizeModel));
   ^~~~~~~~~~~~~~~
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: note: declared here
In file included from /usr/include/pcl-1.8/pcl/sample_consensus/sac_model.h:52:0,
                 from /usr/include/pcl-1.8/pcl/sample_consensus/sac.h:45,
                 from /usr/include/pcl-1.8/pcl/sample_consensus/ransac.h:44,
                 from /usr/include/pcl-1.8/pcl/registration/icp.h:45,
                 from /home/gzxsmapper/ros2_lio_ws/src/li_slam_ros2-master/scanmatcher/include/scanmatcher/utility.h:55,
                 from /home/gzxsmapper/ros2_lio_ws/src/li_slam_ros2-master/scanmatcher/src/imu_preintegration.cpp:31:
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h: In function ‘void __static_initialization_and_destruction_0(int, int)’:
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: warning: ‘pcl::SAC_SAMPLE_SIZE’ is deprecated: This map is deprecated and is kept only to prevent breaking existing user code. Starting from PCL 1.8.0 model sample size is a protected member of the SampleConsensusModel class [-Wdeprecated-declarations]
   SAC_SAMPLE_SIZE (sample_size_pairs, sample_size_pairs + sizeof (sample_size_pairs) / sizeof (SampleSizeModel));
   ^~~~~~~~~~~~~~~
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: note: declared here
make: *** [all] Error 2
---
Failed   <<< scanmatcher [1min 6s, exited with code 2]

**Comment by hunkyu** [comment]
My usage time ubuntu 18.04 ros-dasing

**Comment by hunkyu** [comment]
![Uploading 2020-10-10 17-29-59 的屏幕截图.png…]()

**Comment by rsasaki0109** [comment]
It looks like you wanted to upload an image, but it's not showing up and the link is weird.

**Comment by hunkyu** [comment]
![2020-10-10 23-16-29 的屏幕截图](https://user-images.githubusercontent.com/20533364/95658655-acd61d00-0b4e-11eb-8cac-df490f03f082.png)
The trajectory has drifted, which may be a problem with rosbag. I am using ros2 run ros1_bridge dynamic_bridge --bridge-all-topics

**Comment by rsasaki0109** [comment]
Details, please.

**Comment by JakeReeves21** [comment]
Hello, I have been trying to get ros2 to work with this solution for a few days. I have gotten the rviz2 and ros2 launch scanmatcher commands to run correctly in separate windows.

I have not been able to get the "ros2 bag play -s rosbag_v2 casual_walk.bag" to run correctly in its own window. It cannot read the Velodyne topics, because those topics seem to have been recorded in with ROS 1. Please see below screenshot.

Any ideas on what I am doing incorrectly?


![image](https://user-images.githubusercontent.com/67442357/104508100-5b09bc80-55ad-11eb-8e9b-60f09630c038.png)

**Comment by Gaoeee** [comment]
> scanmatcher prompt: :0:1: error: macro names must be identifiers
> 
> Found in image_projection.cpp `add_executable(image_projection src/image_projection.cpp) ament_target_dependencies(image_projection rclcpp rclcpp_components tf2_ros tf2_geometry_msgs tf2_sensor_msgs tf2_eigen geometry_msgs sensor_msgs nav_msgs #liosam_msgs PCL OpenCV )` I do not compile and generate image_projection, but there is no problem

how did you solve it?
