### ISSUE TITLE
Large velocity reset IMU-preintegration!

### ISSUE THREAD

**Issue by jeychandar** [rsasaki0109/li_slam_ros2#11]
@rsasaki0109 I used li_sam_ros2 repository and tried to run the casual walk bag but it shows deviation and the map doesnot smooth when it processed. It contains lots of noise. can help me out how to solve this issue cuz I am new to this! Thanks in advance.

![image](https://user-images.githubusercontent.com/48254471/209316984-ab5503a5-5899-49df-9688-dd36fc07dee5.png)

**Comment by rsasaki0109** [comment]
Slowing down the playback speed of rosbag might solve the problem.

**Comment by jeychandar** [comment]
> Slowing down the playback speed of rosbag might solve the problem.

@rsasaki0109 "Arigatou gozaimasu" It worked!!! :) .
