### ISSUE TITLE
Fatal error Humble

### ISSUE THREAD

**Issue by argolomb** [rsasaki0109/li_slam_ros2#15]
HI, I'm facing with a fatal error when compiling on humble. 

`graph_based_slam/include/graph_based_slam/graph_based_slam_component.h:47:10: fatal error: tf2_sensor_msgs/tf2_sensor_msgs.h: No such file or directory
   47 | #include <tf2_sensor_msgs/tf2_sensor_msgs.h>`

But all deps are installed, including geometry2 package.

**Comment by rsasaki0109** [comment]
This package is not yet humble-compatible

**Comment by rsasaki0109** [comment]
The following may help you solve the problem.
https://github.com/rsasaki0109/lidarslam_ros2/pull/47

**Comment by argolomb** [comment]
Thanks, work fine.
