### ISSUE TITLE
where choose the lidar points topic?

### ISSUE THREAD

**Issue by FPSychotic** [rsasaki0109/li_slam_ros2#16]
I chosen Livox type, but I cannot find how aim to the livox pointcloud topic, only the imu one
cheers

**Comment by rsasaki0109** [comment]
Add pointCloudTopic to yaml.
After confirming that it works, I will also PR.

https://github.com/rsasaki0109/li_slam_ros2/search?q=pointCloudTopic

**Comment by rsasaki0109** [comment]
The issue regarding the title seems to have been resolved, so we will be closing this matter. If you have any further concerns, please feel free to open a new issue
