### ISSUE TITLE
ppa:borglab/gtsam-release-4.0 not available for ubuntu 22.04

### ISSUE THREAD

**Issue by SamuelHafner** [rsasaki0109/li_slam_ros2#20]
Hello,
just to inform.
The gtsam package is not available for ubuntu 22.04. So it it not running in humble.

Thank you for your work.

Greetings

**Comment by rsasaki0109** [comment]
So, I am planning to implement the Humble support as shown below. 
I have not been able to merge it yet because there are still errors in the CI.

Pull Request
https://github.com/rsasaki0109/li_slam_ros2/pull/14

**Comment by SamuelHafner** [comment]
Thank you for your reply. 

I tried it also with the **ppa:borglab/gtsam-release-4.1** and get more or  less the same error.
![image](https://github.com/rsasaki0109/li_slam_ros2/assets/45936995/9274221d-e854-4c56-8cc0-a27804aa7771)

So I will wait and run it now with foxy. Thank you :)

**Comment by rsasaki0109** [comment]
He has made it compatible with ROS Humble
https://github.com/rsasaki0109/li_slam_ros2/pull/21
