### ISSUE TITLE
Run bag met error gtsam::IndeterminantLinearSystemException

### ISSUE THREAD

**Issue by j953302** [rsasaki0109/li_slam_ros2#23]
Hello, I want to run li_slam with a V16s velodyne lidar and a 9 axis imu. I never change any default parameters in lio.yaml. 

My data is a indoor corridor loop. However, when li_slam run just a little time it occur below problem:
![2023-06-19 13-43-08 的螢幕擷圖](https://github.com/rsasaki0109/li_slam_ros2/assets/48813590/ea2c76bf-d990-44fc-9ddf-6849d5f1565a)

And this is my bag file.
[https://drive.google.com/drive/folders/1Ov5nnFHmqO3qDI_GLPtWwOS9HZtOQiP0?usp=sharing](url)

Could you help me figure it out? Thank you.

**Comment by rsasaki0109** [comment]
I might be too busy this month to look at the rosbag. Could you please post a video of rviz or something similar? 


You might find the link below helpful:
https://github.com/TixiaoShan/LIO-SAM#prepare-imu-data

**Comment by j953302** [comment]
Sure. Let me show you by video. And I consider that my imu and lidar translate matrix is correct because it was successed in the same car with different data.

video:
[https://drive.google.com/file/d/1-0oPejqpnhQVnMYpQvCUqOZNlUn4pwty/view?usp=sharing](url)

**Comment by rsasaki0109** [comment]
@j953302 
I would also like to be provided with a yaml file and launch file.

memo
https://github.com/TixiaoShan/LIO-SAM/issues/165
https://github.com/TixiaoShan/LIO-SAM/issues/167

**Comment by rsasaki0109** [comment]
There may be a problem with imu timestamps.

Helpful comments
> I had this problem too. In my case the reason was that some imu messages were sent with the same timestamp.

https://github.com/TixiaoShan/LIO-SAM/issues/165#issuecomment-1000247782

![image](https://github.com/rsasaki0109/li_slam_ros2/assets/18298605/def3529a-5f57-498e-bbb2-938704fe1be5)
![image](https://github.com/rsasaki0109/li_slam_ros2/assets/18298605/b520ef34-0206-4ae2-ad7c-be0db2b4df8a)

**Comment by j953302** [comment]
@rsasaki0109 Hello, sorry too late to reply.
I have calculate the data. However, in #165 the problem is imu data has same timestamp. But my minimun value dt of  imu data is 0.000043201 s. It's not equal to 0. So I'm not sure #165's solution could help me.
Also, because LIO Sam suggest imu publish frequency up to 200hz. So my data is 200hz

**Comment by j953302** [comment]
@rsasaki0109 Wow, it's really hepful. It fixed my first bug huuuuu...
Thank you.

**Comment by zhao-zhibo** [comment]
My problem was solved. It was a problem with the Eigen version. Changing the expression solved the problem.I asked a question on stackoverflow and someone else answered me.[stackoverflow](https://stackoverflow.com/questions/77627134/gtsam-error-report-assertion-sizeatcompiletime-dynamic-sizeatcompiletim). 
But I don't understand why this can solve the problem. And I don’t understand why this problem occurs?

**Comment by szydgithub** [comment]
> My problem was solved. It was a problem with the Eigen version. Changing the expression solved the problem.I asked a question on stackoverflow and someone else answered me.[stackoverflow](https://stackoverflow.com/questions/77627134/gtsam-error-report-assertion-sizeatcompiletime-dynamic-sizeatcompiletim). But I don't understand why this can solve the problem. And I don’t understand why this problem occurs?

可以具体说一下是如何解决的吗？谢谢
