### ISSUE TITLE
How to Check Mapping Accuracy

### ISSUE THREAD

**Issue by jeychandar** [rsasaki0109/li_slam_ros2#28]
@rsasaki0109 Hi Sir. Since you have working with mapping related field, I am curious to know about the mapping accuracy. Could you guide me how to check mapping accuracy sir. Thanks in advance.

**Comment by rsasaki0109** [comment]
Is it something like comparing with RTK GNSS/IMU? I think the following link may be of reference.
https://github.com/autowarefoundation/autoware-documentation/pull/366
https://autowarefoundation.github.io/autoware-documentation/pr-366/how-to-guides/creating-maps-for-autoware/open-source-slam/compare-slam-algorithms/

**Comment by jeychandar** [comment]
We would like to check the 3D LiDAR mapping accuracy for indoor settings. Eventually the mapped scans will be compared against building information models (e.g. construction progress monitoring & verification).

**Comment by rsasaki0109** [comment]
For indoor references, tracking is often done with total stations. Additionally, for map evaluation, comparisons can be made with floor plans or maps created with ground-based laser scanners.

**Comment by jeychandar** [comment]
Okey sir will check it out

**Comment by rsasaki0109** [comment]
This issue has been inactive for a while and will be closed for housekeeping. If it's still relevant, please feel free to reopen it with a new comment. Thank you for your contribution.
