### ISSUE TITLE
is the git command in readme correct ? 

### ISSUE THREAD

**Issue by jediofgever** [rsasaki0109/li_slam_ros2#3]
Hi , 
I was trying out this package but there is some issue I guess. 
Inn readme you never mention a git command  to clone this repo but instead another repo(again your repo), is this intentional ? 

Could you please check and confirm ? 
Thanks for the awesome work ,

**Comment by rsasaki0109** [comment]
My mistake. Thank you for pointing it out.

**Comment by jediofgever** [comment]
No worries, awesome work already. I am trying to test it in simulation, have had a chance to test this under Gazebo or any other simulation env. ?

**Comment by rsasaki0109** [comment]
Unfortunately, I don't have a good enough PC to simulate lidar, so I haven't tried it.

**Comment by jediofgever** [comment]
I actually tried it , but since I am using navigation, there is quite a lot of message topic confliction. I solvbed some of them but I cant achieve the mapping. The map is constantly shifting.

I am not sure what I am doing wrong here but I guess this could be related to wrong odometry ? , Do you have any suggestions ? 

![Screenshot from 2020-12-16 21-00-46](https://user-images.githubusercontent.com/18460336/102351814-04c35100-3fe2-11eb-9894-888ba0910096.png)

**Comment by rsasaki0109** [comment]
Check if self-positioning can be estimated by mapping using only Lidar.

**Comment by jediofgever** [comment]
unfortunately with perfectly fine simulated lidar data I cant create maps
