### ISSUE TITLE
HOW TO RUN THIS REPO 

### ISSUE THREAD

**Issue by chytra3** [rsasaki0109/li_slam_ros2#32]
hey there i am new here . Can you help me in running this repo .
i have cloned the repo and built .
i would like to know the commands needed to run this.
the commands that i used are :

![image](https://github.com/rsasaki0109/li_slam_ros2/assets/142932821/161fde5a-28cd-406c-9249-ea8e95d1e794)

![image](https://github.com/rsasaki0109/li_slam_ros2/assets/142932821/5bff113a-a958-4d5e-bb2a-49ede5c118c8)

![image](https://github.com/rsasaki0109/li_slam_ros2/assets/142932821/04557661-dc91-468c-be3c-b3001f463f35)

**Comment by rsasaki0109** [comment]
Playing the 'ros2 bag play walking_dataset/' failed. You need to specify the correct path to the bag file.

**Comment by moralessP** [comment]
Hi, how can I find the bag file please? Is it in the repo?

**Comment by rsasaki0109** [comment]
The link to the rosbag can be found in the readme.md file in the repo.

**Comment by rsasaki0109** [comment]
The issue appears to be resolved, so I am closing it. Thank you.
