### ISSUE TITLE
Used Library g2o installation

### ISSUE THREAD

**Issue by rvxfahim** [rsasaki0109/li_slam_ros2#33]
Needed some guidance on the used libraries. It mentions g2o, how do i install it? I have Ubuntu 22 and ros2 humble installed.

**Comment by rsasaki0109** [comment]
You can install g2o using the `rosdep install` command mentioned in the readme.md

**Comment by rsasaki0109** [comment]
Due to inactivity, I'm closing this issue. If there are still concerns, please open a new issue. Thank you.
